#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/takemoto/neuron_kplus/exec"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/takemoto/neuron_kplus/exec/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/takemoto/neuron_kplus/specials/x86_64/.libs/libnrnmech.so" "$@"
